spring:
  application:
    name: study-client

server:
  port: 8760

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/  #配置多个服务注册中心地址，挂掉一个也不怕






